### ISSUE TITLE
I suppose that DJI team should use Carthage or Cocoapods to manage DJISDK.framework.

### ISSUE THREAD

**Issue by lbj96347** [dji-sdk/DJI-Bridge-App#1]
It seems that each DJI project contains a DJISDK.framework.When I clone projects,I may wait for a long time for downloading framework.

I suppose that DJI teams can create a DJISDK.framework project in Carthage or Cocoapods.So developers can use a indepenent way to import this framework.

It would save our time. :-)

**Comment by dji-dev** [comment]
Hi, thanks for your suggestions. Actually, DJI SDK supports Cocoapods now, please check this link for details: https://cocoapods.org/pods/DJI-SDK-iOS, hope this help!
