### ISSUE TITLE
DJI Bridge App Port?

### ISSUE THREAD

**Issue by brianwallace** [dji-sdk/DJI-Bridge-App#5]
Does anyone know which port(s) the DJI Bridge App runs on?

CC @jonathanreeves

**Comment by brianwallace** [comment]
From our assessment, the DJI debug bridge uses 7001 - 7006 and 7070.  If anyone can help to confirm this, it would be appreciated.

**Comment by oliverou** [comment]
Hi @brianwallace, yes, you have already tested it. The DJI Bridge App is already open source, you can customize it by yourself.
