### ISSUE TITLE
Where is the DJI-SDK-iOS 4.3.1.1

### ISSUE THREAD

**Issue by sunnyyoung** [dji-sdk/DJI-Bridge-App#6]
The `Podfile` from latest release using the `DJI-SDK-iOS 4.3.1.1`, but where is the `DJI-SDK-iOS 4.3.1.1`? After I do `pod repo update`, it still can not find the DJI-SDK-iOS 4.3.1.1.

**Comment by oliverou** [comment]
Hi @Sunnyyoung , please fetch the latest Podfile, it's fixed. We only have DJI iOS SDK 4.3.1. Sorry for the confusion.

**Comment by oliverou** [comment]
Hi @Sunnyyoung , the iOS-Bridge-App repo will not be compatible with the new SDK 4.3.1, please download the new DJI SDK Bridge app from App Store: <https://itunes.apple.com/us/app/sdk-bridge/id1263583917?ls=1&mt=8>.

**Comment by sunnyyoung** [comment]
@oliverou Great thanks, ~~but I wonder why unavailable in China AppStore.~~
I found it, it also available in China AppStore too. 😂

**Comment by oliverou** [comment]
Hi @Sunnyyoung , it's available in China App Store, please check this link: <https://itunes.apple.com/cn/app/sdk-bridge/id1263583917?ls=1&mt=8>
