### ISSUE TITLE
Bullshit

### ISSUE THREAD

**Issue by neilyoung** [dji-sdk/DJI-Bridge-App#8]
...nothing more to say.

Try to run it (as bridge) on iOS 15.3 and on Android on the other side. No chance to make that work. Left icon green. OK. Right is red, remains red. Rubbish, not going to work

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59949'>Zendesk ticket #59949</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/59949'>Zendesk ticket #59949</a>:<br><br>If you just want to use the IOS SDK Bridge app, please go to the App Store to install it.
 ![](https://djisdksupport.zendesk.com/attachments/token/P5hktf0cmDgUQaiVevuakT0wC/?name=inline748830530.png)​

And if you run the MSDK sample failed, could you please provide more information about your operation and the issue:

1. Aircraft type and firmware version.
2. MSDK version.
3. The video about your operation and issue( please use google drive or dropbox to send the video ).<br><a href='https://djisdksupport.zendesk.com/attachments/token/P5hktf0cmDgUQaiVevuakT0wC' target='zd_attach'>inline748830530.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by neilyoung** [comment]
I did that. Doesn't work between Android and iOS

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/59949'>Zendesk ticket #59949</a>:<br><br>If you want to make a bridge between Android and IOS, and you want to use the Android sample to run on IOS, that will not work.

The IOS Bridge App is for you to debug your IOS MSDK App on Mac, and dose not need to install the app to the IOS device for debuging.

I used the IOS Bridge App often, and it could work normally.

If you usr the IOS Bridge App failed, it`s recommended to provide the video about your operation and issue for us further check.
<br><p><em><small>°°°</small></em></p>

**Comment by neilyoung** [comment]
No, I will not run the Android app on iOS. I wanted to do, what your app promises: Bridge an RC to the Android device as if it would be plugged at USB. I wanted to overcome the debug difficulties with Android. Debugging over Wifi is a pain in the ass to say it gently. Sometimes it works, mostly it doesn't and you have half an hour trouble to reestablish everything once the connection gets lost.

So I plugged the RC to my iPhone and fired up the bridge app. The RC is detected. On the other end is an Android Studio, a real Android device plugged via USB. The Android code tries to use TCP in order to use the RC. That doesn't work. 

I thought it would work like so.

**Comment by neilyoung** [comment]
The only thing I see in Wireshark are ARP requests, trying to resolve the IP which is shown in the iOS app: 192.168.188.24.

Obviously w/o success, because the requests repeat.

This does not work.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/731020/152763449-809eb2c1-70ba-4a49-b746-310f03553621.png">

**Comment by neilyoung** [comment]
But for sure, the iOS TCP is different from the Android TCP :)))

**Comment by neilyoung** [comment]
Also observed...

![image](https://user-images.githubusercontent.com/731020/152765047-cf101697-f41d-41f6-b2ef-4a896c456f06.png)

**Comment by neilyoung** [comment]
After having figured out the _real_ IP4 of my iPhone (from settings) and re-started this "app" as many times as it needed until it displayed that IP I see at least some ~~TLS traffic~~ binary traffic between Android and iOS. But this does neither make the Wifi icon green nor let the Android app start properly.

Rubbish...

**Comment by neilyoung** [comment]
Well, disregard. Not worth to mess with that crap
